"""add site_table and site_member for site-centric multi-tenancy

Revision ID: 0c5152c88bf5
Revises: 5532d8bb87b8
Create Date: 2026-08-03 23:58:33.831088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5152c88bf5'
down_revision: Union[str, Sequence[str], None] = '5532d8bb87b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_table',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(16), nullable=False),
    sa.Column('site_name', sa.String(64), nullable=False),
    sa.Column('site_location', sa.String(128), nullable=True),
    sa.Column('site_owner_id', sa.String(), nullable=False),
    sa.Column('site_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_owner_id'], ['user_table.usr_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_index(op.f('ix_site_table_org_id'), 'site_table', ['org_id'], unique=True)
    op.create_index(op.f('ix_site_table_site_name'), 'site_table', ['site_name'], unique=False)
    op.create_index(op.f('ix_site_table_site_owner_id'), 'site_table', ['site_owner_id'], unique=False)
    op.create_table('site_member',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('usr_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('joined_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site_table.site_id'], ),
    sa.ForeignKeyConstraint(['usr_id'], ['user_table.usr_id'], ),
    sa.PrimaryKeyConstraint('site_id', 'usr_id')
    )
    op.add_column('device_information', sa.Column('site_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_owner_serial_fp'), 'device_information', type_='unique')
    op.create_index(op.f('ix_device_information_site_id'), 'device_information', ['site_id'], unique=False)
    op.create_unique_constraint('uq_site_serial_fp', 'device_information', ['site_id', 'dev_serial', 'dev_fingerprint'])
    op.create_foreign_key(None, 'device_information', 'site_table', ['site_id'], ['site_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_information', type_='foreignkey')
    op.drop_constraint('uq_site_serial_fp', 'device_information', type_='unique')
    op.drop_index(op.f('ix_device_information_site_id'), table_name='device_information')
    op.create_unique_constraint(op.f('uq_owner_serial_fp'), 'device_information', ['dev_owner_id', 'dev_serial', 'dev_fingerprint'], postgresql_nulls_not_distinct=False)
    op.drop_column('device_information', 'site_id')
    op.drop_table('site_member')
    op.drop_index(op.f('ix_site_table_site_owner_id'), table_name='site_table')
    op.drop_index(op.f('ix_site_table_site_name'), table_name='site_table')
    op.drop_index(op.f('ix_site_table_org_id'), table_name='site_table')
    op.drop_table('site_table')
    # ### end Alembic commands ###
