"""enforce one capability row per device

Revision ID: 1c27ad08528c
Revises: cf6fa7c0122e
Create Date: 2026-07-12 13:03:28.657261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c27ad08528c'
down_revision: Union[str, Sequence[str], None] = 'cf6fa7c0122e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_capability_dev_id', 'device_capability', ['cap_dev_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_capability_dev_id', 'device_capability', type_='unique')
    # ### end Alembic commands ###
