"""make device owner_id nullable for pending call-home devices

Revision ID: 2670dda1a44f
Revises: 1c27ad08528c
Create Date: 2026-07-12 13:18:06.239083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2670dda1a44f'
down_revision: Union[str, Sequence[str], None] = '1c27ad08528c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_information', 'dev_owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_information', 'dev_owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
