"""Dev_Info_UNQ_SER_N_FP

Revision ID: 2d9c777f54b8
Revises: 290370dd2b50
Create Date: 2026-08-26 20:45:45.759653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9c777f54b8'
down_revision: Union[str, Sequence[str], None] = '290370dd2b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_site_serial_fp'), 'device_information', type_='unique')
    op.create_unique_constraint('unique_serial_n_fingerprint', 'device_information', ['dev_serial', 'dev_fingerprint'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_serial_n_fingerprint', 'device_information', type_='unique')
    op.create_unique_constraint(op.f('uq_site_serial_fp'), 'device_information', ['site_id', 'dev_serial', 'dev_fingerprint'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###
