"""merge bootstrap token key and config resource into one

Revision ID: 429765f8c957
Revises: 3f0108bc1df6
Create Date: 2026-07-29 11:55:18.947291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '429765f8c957'
down_revision: Union[str, Sequence[str], None] = '3f0108bc1df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default ชั่วคราวตอน add column (กันพังกับแถวทดสอบเก่าที่มีอยู่แล้ว
    # จากรอบก่อน) ตัด default ออกหลัง backfill เสร็จเพราะ model ฝั่ง Python ตั้ง
    # default=False เองอยู่แล้ว ไม่ต้องพึ่ง DB-side default ต่อไป
    op.add_column('bootstrap_token', sa.Column('bst_used', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('bootstrap_token', sa.Column('bst_used_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('bootstrap_token', 'bst_used', server_default=None)
    op.drop_column('bootstrap_token', 'bst_config_used')
    op.drop_column('bootstrap_token', 'bst_key_used')
    op.drop_column('bootstrap_token', 'bst_config_used_at')
    op.drop_column('bootstrap_token', 'bst_key_used_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bootstrap_token', sa.Column('bst_key_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bootstrap_token', sa.Column('bst_config_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bootstrap_token', sa.Column('bst_key_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('bootstrap_token', sa.Column('bst_config_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('bootstrap_token', 'bst_used_at')
    op.drop_column('bootstrap_token', 'bst_used')
    # ### end Alembic commands ###
