"""add index to user_id in each table

Revision ID: 7fc10b1e11ed
Revises: a59b2eddba53
Create Date: 2026-08-31 12:09:48.340414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc10b1e11ed'
down_revision: Union[str, Sequence[str], None] = 'a59b2eddba53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_config_reference')
    op.create_index(op.f('ix_device_access_acc_usr_id'), 'device_access', ['acc_usr_id'], unique=False)
    op.create_index(op.f('ix_device_config_object_cfg_created_by_id'), 'device_config_object', ['cfg_created_by_id'], unique=False)
    op.create_index(op.f('ix_device_history_his_usr_id'), 'device_history', ['his_usr_id'], unique=False)
    op.create_index(op.f('ix_site_member_usr_id'), 'site_member', ['usr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_member_usr_id'), table_name='site_member')
    op.drop_index(op.f('ix_device_history_his_usr_id'), table_name='device_history')
    op.drop_index(op.f('ix_device_config_object_cfg_created_by_id'), table_name='device_config_object')
    op.drop_index(op.f('ix_device_access_acc_usr_id'), table_name='device_access')
    op.create_table('device_config_reference',
    sa.Column('ref_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ref_from_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ref_to_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ref_from_id'], ['device_config_object.cfg_id'], name=op.f('device_config_reference_ref_from_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_to_id'], ['device_config_object.cfg_id'], name=op.f('device_config_reference_ref_to_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ref_id', name=op.f('device_config_reference_pkey')),
    sa.UniqueConstraint('ref_from_id', 'ref_to_id', name=op.f('uq_ref_from_to'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
