"""add device config object and reference tables

Revision ID: 8ff09edbbc47
Revises: f0b0bf3e3d15
Create Date: 2026-07-23 10:04:33.545993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff09edbbc47'
down_revision: Union[str, Sequence[str], None] = 'f0b0bf3e3d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_config_object',
    sa.Column('cfg_id', sa.String(), nullable=False),
    sa.Column('cfg_feature', sa.String(), nullable=False),
    sa.Column('cfg_name', sa.String(), nullable=False),
    sa.Column('cfg_params', sa.String(), nullable=False),
    sa.Column('cfg_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cfg_dev_id', sa.String(), nullable=False),
    sa.Column('cfg_created_by_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cfg_created_by_id'], ['user_table.usr_id'], ),
    sa.ForeignKeyConstraint(['cfg_dev_id'], ['device_information.dev_id'], ),
    sa.PrimaryKeyConstraint('cfg_id'),
    sa.UniqueConstraint('cfg_dev_id', 'cfg_feature', 'cfg_name', name='uq_cfg_dev_feature_name')
    )
    op.create_index(op.f('ix_device_config_object_cfg_dev_id'), 'device_config_object', ['cfg_dev_id'], unique=False)
    op.create_index(op.f('ix_device_config_object_cfg_feature'), 'device_config_object', ['cfg_feature'], unique=False)
    op.create_index(op.f('ix_device_config_object_cfg_name'), 'device_config_object', ['cfg_name'], unique=False)
    op.create_table('device_config_reference',
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('ref_from_id', sa.String(), nullable=False),
    sa.Column('ref_to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ref_from_id'], ['device_config_object.cfg_id'], ),
    sa.ForeignKeyConstraint(['ref_to_id'], ['device_config_object.cfg_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ref_id'),
    sa.UniqueConstraint('ref_from_id', 'ref_to_id', name='uq_ref_from_to')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_config_reference')
    op.drop_index(op.f('ix_device_config_object_cfg_name'), table_name='device_config_object')
    op.drop_index(op.f('ix_device_config_object_cfg_feature'), table_name='device_config_object')
    op.drop_index(op.f('ix_device_config_object_cfg_dev_id'), table_name='device_config_object')
    op.drop_table('device_config_object')
    # ### end Alembic commands ###
