"""add index to his_dev_id & acc_dev_id

Revision ID: a59b2eddba53
Revises: d2c27e07f2d6
Create Date: 2026-08-30 16:15:18.224860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59b2eddba53'
down_revision: Union[str, Sequence[str], None] = 'd2c27e07f2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_device_access_acc_dev_id'), 'device_access', ['acc_dev_id'], unique=False)
    op.create_index(op.f('ix_device_history_his_dev_id'), 'device_history', ['his_dev_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_history_his_dev_id'), table_name='device_history')
    op.drop_index(op.f('ix_device_access_acc_dev_id'), table_name='device_access')
    # ### end Alembic commands ###
