"""cascade delete for device config reference ref_from_id

Revision ID: adc0f5952375
Revises: 8ff09edbbc47
Create Date: 2026-07-23 10:16:41.593335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc0f5952375'
down_revision: Union[str, Sequence[str], None] = '8ff09edbbc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('device_config_reference_ref_from_id_fkey'), 'device_config_reference', type_='foreignkey')
    op.create_foreign_key(None, 'device_config_reference', 'device_config_object', ['ref_from_id'], ['cfg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_config_reference', type_='foreignkey')
    op.create_foreign_key(op.f('device_config_reference_ref_from_id_fkey'), 'device_config_reference', 'device_config_object', ['ref_from_id'], ['cfg_id'])
    # ### end Alembic commands ###
