"""comment

Revision ID: cf6fa7c0122e
Revises: 
Create Date: 2026-07-11 23:39:59.529005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf6fa7c0122e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('usr_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usr_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('usr_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usr_passwd', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usr_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usr_created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_email')
    )
    op.create_index(op.f('ix_user_table_usr_name'), 'user_table', ['usr_name'], unique=True)
    op.create_table('device_group',
    sa.Column('grp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grp_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('grp_desc', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('grp_created_date', sa.DateTime(), nullable=False),
    sa.Column('grp_creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['grp_creator_id'], ['user_table.usr_id'], ),
    sa.PrimaryKeyConstraint('grp_id')
    )
    op.create_table('device_information',
    sa.Column('dev_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dev_vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dev_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dev_firmware', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dev_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dev_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dev_source_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dev_mac', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dev_serial', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dev_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dev_behide_nat', sa.Boolean(), nullable=False),
    sa.Column('dev_cloned', sa.Boolean(), nullable=False),
    sa.Column('dev_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dev_registered', sa.Boolean(), nullable=False),
    sa.Column('dev_added_date', sa.DateTime(), nullable=False),
    sa.Column('dev_last_seen', sa.DateTime(), nullable=True),
    sa.Column('dev_owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['dev_owner_id'], ['user_table.usr_id'], ),
    sa.PrimaryKeyConstraint('dev_id'),
    sa.UniqueConstraint('dev_owner_id', 'dev_serial', 'dev_fingerprint', name='uq_owner_serial_fp')
    )
    op.create_index(op.f('ix_device_information_dev_fingerprint'), 'device_information', ['dev_fingerprint'], unique=False)
    op.create_index(op.f('ix_device_information_dev_mac'), 'device_information', ['dev_mac'], unique=False)
    op.create_index(op.f('ix_device_information_dev_serial'), 'device_information', ['dev_serial'], unique=False)
    op.create_index(op.f('ix_device_information_dev_status'), 'device_information', ['dev_status'], unique=False)
    op.create_table('device_access',
    sa.Column('acc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acc_date', sa.DateTime(), nullable=False),
    sa.Column('acc_lastseen', sa.DateTime(), nullable=False),
    sa.Column('acc_dev_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acc_usr_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['acc_dev_id'], ['device_information.dev_id'], ),
    sa.ForeignKeyConstraint(['acc_usr_id'], ['user_table.usr_id'], ),
    sa.PrimaryKeyConstraint('acc_id')
    )
    op.create_table('device_capability',
    sa.Column('cap_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cap_vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cap_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cap_saved_date', sa.DateTime(), nullable=False),
    sa.Column('cap_dev_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cap_dev_id'], ['device_information.dev_id'], ),
    sa.PrimaryKeyConstraint('cap_id')
    )
    op.create_table('device_group_member',
    sa.Column('dev_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['dev_id'], ['device_information.dev_id'], ),
    sa.ForeignKeyConstraint(['grp_id'], ['device_group.grp_id'], ),
    sa.PrimaryKeyConstraint('dev_id', 'grp_id')
    )
    op.create_table('device_history',
    sa.Column('his_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('his_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('his_action_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('his_action_time', sa.DateTime(), nullable=False),
    sa.Column('his_dev_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('his_usr_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['his_dev_id'], ['device_information.dev_id'], ),
    sa.ForeignKeyConstraint(['his_usr_id'], ['user_table.usr_id'], ),
    sa.PrimaryKeyConstraint('his_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_history')
    op.drop_table('device_group_member')
    op.drop_table('device_capability')
    op.drop_table('device_access')
    op.drop_index(op.f('ix_device_information_dev_status'), table_name='device_information')
    op.drop_index(op.f('ix_device_information_dev_serial'), table_name='device_information')
    op.drop_index(op.f('ix_device_information_dev_mac'), table_name='device_information')
    op.drop_index(op.f('ix_device_information_dev_fingerprint'), table_name='device_information')
    op.drop_table('device_information')
    op.drop_table('device_group')
    op.drop_index(op.f('ix_user_table_usr_name'), table_name='user_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
