"""site-centric v2: simplify site relationships, require device.site_id, drop device_group

Revision ID: e2579de9da29
Revises: 0c5152c88bf5
Create Date: 2026-08-04 00:34:02.980540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2579de9da29'
down_revision: Union[str, Sequence[str], None] = '0c5152c88bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # เจอบั๊กจริงตอนรัน migration (2026-08-04): alembic autogenerate เรียง
    # drop_table('device_group') ก่อน drop_table('device_group_member') แต่
    # device_group_member มี FK ชี้ไปที่ device_group (grp_id) อยู่ - ต้องลบ
    # ตารางที่ "อ้างอิงคนอื่น" (device_group_member) ก่อนเสมอ แล้วค่อยลบตารางที่
    # "ถูกอ้างอิง" (device_group) ทีหลัง (สลับลำดับที่ autogenerate ให้มา)
    op.drop_table('device_group_member')
    op.drop_table('device_group')

    # user ขอ (2026-08-04): "Amano Data Migration Script" - โอนย้ายอุปกรณ์เดิม
    # ทั้งหมดของ user amano (org_id="ORG-MAIN01", site_name="main site") เข้า
    # site ใหม่นี้ก่อนเสมอ ต้องทำ**ก่อน** ALTER COLUMN...SET NOT NULL ด้านล่าง
    # เพราะทุกแถวใน device_information ตอนนี้ site_id ยังเป็น NULL อยู่ทั้งหมด
    # (เพิ่ง add column แบบ nullable ไว้ในรอบก่อน - migration 0c5152c88bf5) ถ้า
    # ไม่เติมให้ครบก่อน ALTER COLUMN จะพังทันทีด้วย NOT NULL constraint
    # violation - **ย้ายอุปกรณ์ทุกแถวที่ site_id ยังเป็น NULL เข้า main site
    # เดียวกันหมด** ไม่ใช่แค่ของ amano เท่านั้น (รวมแถวที่ไม่มีเจ้าของเลยด้วย -
    # เช่นอุปกรณ์ที่เคย call-home มาก่อนแต่ไม่มีใคร claim - ไม่งั้นแถวพวกนั้นจะ
    # เหลือ site_id=NULL ค้างชน constraint อยู่ดี) - ใช้ sa.table()/sa.column()
    # (lightweight reflection ผ่าน Core ไม่ import ORM model จริงเข้ามาใน
    # migration file - กัน migration นี้พังถ้า model เปลี่ยนต่อในอนาคต)
    import uuid
    from datetime import datetime, timezone

    connection = op.get_bind()

    site_table = sa.table(
        'site_table',
        sa.column('site_id', sa.String),
        sa.column('org_id', sa.String),
        sa.column('site_name', sa.String),
        sa.column('site_location', sa.String),
        sa.column('site_owner_id', sa.String),
        sa.column('site_created_date', sa.DateTime(timezone=True)),
    )
    user_table = sa.table('user_table', sa.column('usr_id', sa.String), sa.column('usr_name', sa.String))
    device_table = sa.table('device_information', sa.column('dev_id', sa.String), sa.column('site_id', sa.String))

    amano = connection.execute(
        sa.select(user_table.c.usr_id).where(user_table.c.usr_name == 'amano')
    ).first()

    if amano is not None:
        # uuid7 (ที่ backend/model/models.py ใช้จริงตอน runtime) ไม่มีให้เรียกใน
        # SQLAlchemy Core เฉยๆ - ใช้ uuid4 แทนสำหรับ id เดียวที่ migration นี้
        # ต้องสร้างเอง (ไม่กระทบอะไรเพราะทั้ง frontend/backend อ่าน site_id เป็น
        # string ธรรมดา ไม่เคย parse โครงสร้าง uuid7 จริงจังที่ไหนเลย)
        new_site_id = f"site_{uuid.uuid4().hex}"
        connection.execute(
            site_table.insert().values(
                site_id=new_site_id,
                org_id="ORG-MAIN01",
                site_name="main site",
                site_location=None,
                site_owner_id=amano.usr_id,
                site_created_date=datetime.now(timezone.utc),
            )
        )
        connection.execute(
            device_table.update()
            .where(device_table.c.site_id.is_(None))
            .values(site_id=new_site_id)
        )

    op.alter_column('device_information', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('device_information_dev_owner_id_fkey'), 'device_information', type_='foreignkey')
    op.drop_column('device_information', 'dev_owner_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_information', sa.Column('dev_owner_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('device_information_dev_owner_id_fkey'), 'device_information', 'user_table', ['dev_owner_id'], ['usr_id'])
    op.alter_column('device_information', 'site_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # เจอบั๊กเดียวกันกับ upgrade() - ต้องสร้างตารางที่ "ถูกอ้างอิง" (device_group)
    # ก่อนตารางที่ "อ้างอิงคนอื่น" (device_group_member) เสมอ (สลับลำดับที่
    # autogenerate ให้มา)
    op.create_table('device_group',
    sa.Column('grp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('grp_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('grp_desc', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('grp_created_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('grp_creator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grp_creator_id'], ['user_table.usr_id'], name=op.f('device_group_grp_creator_id_fkey')),
    sa.PrimaryKeyConstraint('grp_id', name=op.f('device_group_pkey'))
    )
    op.create_table('device_group_member',
    sa.Column('dev_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('grp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dev_id'], ['device_information.dev_id'], name=op.f('device_group_member_dev_id_fkey')),
    sa.ForeignKeyConstraint(['grp_id'], ['device_group.grp_id'], name=op.f('device_group_member_grp_id_fkey')),
    sa.PrimaryKeyConstraint('dev_id', 'grp_id', name=op.f('device_group_member_pkey'))
    )
    # ### end Alembic commands ###
