"""add bootstrap token table

Revision ID: edcf235e800c
Revises: adc0f5952375
Create Date: 2026-07-29 11:22:25.545532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edcf235e800c'
down_revision: Union[str, Sequence[str], None] = 'adc0f5952375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bootstrap_token',
    sa.Column('bst_token', sa.String(), nullable=False),
    sa.Column('bst_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bst_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bst_used', sa.Boolean(), nullable=False),
    sa.Column('bst_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bst_used_from_ip', sa.String(), nullable=True),
    sa.Column('bst_usr_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bst_usr_id'], ['user_table.usr_id'], ),
    sa.PrimaryKeyConstraint('bst_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bootstrap_token')
    # ### end Alembic commands ###
